"""Added params

Revision ID: 8c204f4b8f2f
Revises: 83ab98dd318e
Create Date: 2025-06-09 11:29:41.841583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c204f4b8f2f'
down_revision: Union[str, None] = '83ab98dd318e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_results', sa.Column('params', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_results', 'params')
    # ### end Alembic commands ###
